[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["lazy_static"]

[dependencies]
lazy_static = { version = "1.4.0", optional = true }

[dev-dependencies]
rand = "0.8.4"
