[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
byte-slice-cast = { version = "1.2.0", default-features = false }

[dev-dependencies]
rand = "0.8.4"
